from app.crud.aula import *
from app.crud.carrera import *
from app.crud.croquis import *
from app.crud.curso import *
from app.crud.curso_aula import *
from app.crud.curso_horario import *
from app.crud.docente import *
from app.crud.docente_carrera import *
from app.crud.docente_materia import *
from app.crud.docente_sala import *
from app.crud.docente_vinculacion import *
from app.crud.escritorio import *
from app.crud.horario import *
from app.crud.materia import *
from app.crud.materia_carrera import *
from app.crud.notificacion import *
from app.crud.permiso import *
from app.crud.plaza import *
from app.crud.reserva import *
from app.crud.rol import *
from app.crud.rol_permiso import *
from app.crud.sala import *
from app.crud.sala_carrera import *
from app.crud.sala_profesores import *
from app.crud.sede import *
from app.crud.usuario import *
from app.crud.usuario_rol import *